language: go

go:
- 1.14

branches:
  only:
  - master

before_script:
- sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass '123456'

script:
- go get -t -v ./...
- bash ./test.sh

after_success:
- bash <(curl -s https://codecov.io/bash)
